AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
Metrics/AbcSize:
  Exclude:
    - 'db/**/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/*'
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Exclude:
    - 'db/**/*'
Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'
Style/Documentation:
  Exclude:
    - 'app/controllers/application_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'
    - 'db/**/*'
